language: android
install: 
  - sudo apt install -y ant
android:
  components:
    - build-tools-21.1.1
    - android-21
    - tools
    - platform-tools
  licenses:
    - 'android-sdk-license-.+'


script:
    - ant setup
    - ant compile_local
    - ant dist
    - ant debug

cache:
  directories:
    - $HOME/.android

branches:
  only:
    - master
    - /^rel-.*$/

#addons:
#  artifacts:
#    paths:
#      - bin/*-debug.apk
#      - ./*.jar
